
branches:
  only:
    - master

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - liblzma-dev
      - gcc-9
      - g++-9
      - clang-8

matrix:
  include:
    - os: linux
      language: python
      python: 2.7
    - os: linux
      language: python
      python: 3.5
    - os: linux
      language: python
      python: 3.6
    - os: linux
      language: python
      python: 3.7
      dist: xenial
      sudo: true
    - os: osx
      language: generic

env:
  - CXX=g++-9 CC=gcc-9
  - CXX=clang++-8 CC=clang-8

install:
  - pip install -U tox-travis coveralls pip setuptools wheel pytest
  - pip install -v -e .

before_script:
  - ${CXX} --version
  - ${CC} --version
  - python --version

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then tox; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pytest -v --pyargs numcodecs; fi

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then coveralls; fi

